# Generated by Django 5.2.7 on 2025-11-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceActividad',
            fields=[
                ('id_enlace', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_enlace', models.IntegerField(choices=[(0, 'FC - Fin-Comienzo (Finish-to-Start)'), (1, 'CC - Comienzo-Comienzo (Start-to-Start)'), (2, 'FF - Fin-Fin (Finish-to-Finish)'), (3, 'CF - Comienzo-Fin (Start-to-Finish)')], default=0, verbose_name='Tipo de Enlace')),
                ('lag', models.IntegerField(default=0, verbose_name='Retraso (días)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('actividad_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_como_destino', to='proyectos.actividad', verbose_name='Actividad Sucesora')),
                ('actividad_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_como_origen', to='proyectos.actividad', verbose_name='Actividad Predecesora')),
            ],
            options={
                'verbose_name': 'Enlace entre Actividades',
                'verbose_name_plural': 'Enlaces entre Actividades',
                'db_table': 'proyectos_enlaces_actividades',
                'unique_together': {('actividad_origen', 'actividad_destino')},
            },
        ),
    ]
