# Generated by Django 5.2.7 on 2025-11-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(help_text='NIT o número de identificación único del cliente', max_length=20, unique=True, verbose_name='Número de Documento/NIT')),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa o persona', max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre con el que se conoce comercialmente (opcional)', max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('representante_legal', models.CharField(blank=True, help_text='Nombre del representante legal', max_length=150, null=True, verbose_name='Representante Legal')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Secundario')),
                ('email_principal', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Secundario')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('sitio_web', models.URLField(blank=True, help_text='URL del sitio web del cliente (opcional)', null=True, verbose_name='Sitio Web')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, help_text='Si el cliente está activo en el sistema', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'proyectos_clientes',
                'ordering': ['razon_social'],
            },
        ),
    ]
