# Generated by Django 5.2.7 on 2025-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_enlaceactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciafotografica',
            name='fecha_captura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Captura'),
        ),
    ]
