# Generated by Django 5.2.7 on 2025-11-15 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id_estado_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(help_text='Ej: Planificación, En ejecución, Finalizado', max_length=50, unique=True, verbose_name='Nombre del Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del estado', null=True, verbose_name='Descripción')),
                ('color_badge', models.CharField(default='secondary', help_text='Color Bootstrap para el badge. Ej: primary, success, danger, warning', max_length=20, verbose_name='Color del Badge')),
                ('permite_edicion', models.BooleanField(default=True, help_text='Si permite modificar actividades y datos del proyecto en este estado', verbose_name='Permite Edición')),
                ('es_estado_final', models.BooleanField(default=False, help_text='Marca como estado final (Finalizado, Cancelado)', verbose_name='Es Estado Final')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que aparece en listas y filtros', verbose_name='Orden de Visualización')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para usar en proyectos', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyectos',
                'db_table': 'proyectos_estados',
                'ordering': ['orden_visualizacion', 'nombre_estado'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoProyecto',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(help_text='Ej: Contrato, Plano estructural, Licencia, Acta de inicio', max_length=100, unique=True, verbose_name='Nombre del Tipo de Documento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de documento', null=True, verbose_name='Descripción')),
                ('requiere_vigencia', models.BooleanField(default=False, help_text='Si este tipo de documento tiene fecha de vencimiento', verbose_name='Requiere Control de Vigencia')),
                ('dias_alerta_vencimiento', models.IntegerField(default=30, help_text='Días antes del vencimiento para generar alerta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días de Alerta')),
                ('icono', models.CharField(blank=True, help_text='Clase de Bootstrap Icons. Ej: bi-file-earmark-text', max_length=50, null=True, verbose_name='Icono')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que aparece en listas', verbose_name='Orden de Visualización')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para usar en proyectos', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Proyecto',
                'verbose_name_plural': 'Tipos de Documentos de Proyectos',
                'db_table': 'proyectos_tipos_documentos',
                'ordering': ['orden_visualizacion', 'nombre_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id_tipo_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(help_text='Ej: Fabricación e instalación de carpas, Adoquinado peatonal, Redes eléctricas', max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del tipo de proyecto', null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Clase de Bootstrap Icons. Ej: bi-building, bi-tools', max_length=50, null=True, verbose_name='Icono')),
                ('color_identificador', models.CharField(default='primary', help_text='Color para badges y visualización. Ej: primary, success, warning, info', max_length=20, verbose_name='Color Identificador')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para usar en nuevos proyectos', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyectos',
                'db_table': 'proyectos_tipos',
                'ordering': ['nombre_tipo'],
            },
        ),
    ]
