# Generated by Django 5.2.7 on 2025-11-15 21:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_cliente'),
        ('trabajadores', '0012_tipodocumento_trabajadordocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento/NIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='color_badge',
            field=models.CharField(default='secondary', help_text='Color para badges: primary, secondary, success, danger, warning, info', max_length=20, verbose_name='Color del Badge'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='es_estado_final',
            field=models.BooleanField(default=False, help_text='Indica si es un estado final del proyecto', verbose_name='Es Estado Final'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='nombre_estado',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Estado'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='orden_visualizacion',
            field=models.IntegerField(default=0, verbose_name='Orden de Visualización'),
        ),
        migrations.AlterField(
            model_name='estadoproyecto',
            name='permite_edicion',
            field=models.BooleanField(default=True, help_text='Si permite editar el proyecto en este estado', verbose_name='Permite Edición'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='dias_alerta_vencimiento',
            field=models.IntegerField(default=30, verbose_name='Días de Alerta antes del Vencimiento'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de icono de Bootstrap Icons', max_length=50, null=True, verbose_name='Icono Bootstrap'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='nombre_tipo_documento',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='orden_visualizacion',
            field=models.IntegerField(default=0, verbose_name='Orden de Visualización'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoproyecto',
            name='requiere_vigencia',
            field=models.BooleanField(default=False, help_text='Si el documento tiene fecha de vencimiento', verbose_name='Requiere Control de Vigencia'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='color_identificador',
            field=models.CharField(default='primary', help_text='Color para badges: primary, secondary, success, danger, warning, info', max_length=20, verbose_name='Color Identificador'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de icono de Bootstrap Icons. Ej: bi-hammer', max_length=50, null=True, verbose_name='Icono Bootstrap'),
        ),
        migrations.AlterField(
            model_name='tipoproyecto',
            name='nombre_tipo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Proyecto'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('numero_actividad', models.CharField(help_text='Ej: 4.1, 4.1.1, 4.1.2', max_length=20, verbose_name='Número de Actividad')),
                ('nombre_actividad', models.CharField(max_length=200, verbose_name='Nombre de la Actividad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, help_text='De 0 a 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Avance')),
                ('peso_actividad', models.DecimalField(decimal_places=2, default=1, help_text='Peso relativo para cálculo de avance del proyecto', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso de la Actividad')),
                ('fecha_inicio_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Estimada')),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Estimada')),
                ('fecha_inicio_real', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Real')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('orden_visualizacion', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('actividad_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subactividades', to='proyectos.actividad', verbose_name='Actividad Padre')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'proyectos_actividades',
                'ordering': ['proyecto', 'orden_visualizacion', 'numero_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_proyecto', models.CharField(max_length=50, unique=True, verbose_name='Código del Proyecto')),
                ('nombre_proyecto', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('ingeniero_responsable', models.CharField(max_length=150, verbose_name='Ingeniero Responsable')),
                ('cargo_responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Responsable')),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Responsable')),
                ('direccion_proyecto', models.CharField(max_length=200, verbose_name='Dirección del Proyecto')),
                ('ciudad_proyecto', models.CharField(max_length=100, verbose_name='Ciudad del Proyecto')),
                ('departamento_proyecto', models.CharField(max_length=100, verbose_name='Departamento del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Fin Estimada')),
                ('fecha_fin_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Real')),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto Estimado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.cliente', verbose_name='Cliente')),
                ('estado_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_estado', to='proyectos.estadoproyecto', verbose_name='Estado del Proyecto')),
                ('tipo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='proyectos.tipoproyecto', verbose_name='Tipo de Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos_proyectos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_evidencia', models.CharField(choices=[('INICIO', 'Inicio del Proyecto'), ('AVANCE', 'Avance de Obra'), ('PROBLEMA', 'Problema o Incidencia'), ('SOLUCION', 'Solución Aplicada'), ('CALIDAD', 'Control de Calidad'), ('FINAL', 'Finalización del Proyecto'), ('OTRO', 'Otro')], default='AVANCE', max_length=20, verbose_name='Tipo de Evidencia')),
                ('imagen', models.ImageField(upload_to='proyectos/evidencias/%Y/%m/', verbose_name='Imagen')),
                ('fecha_captura', models.DateField(verbose_name='Fecha de Captura')),
                ('ubicacion_descripcion', models.CharField(blank=True, help_text='Descripción de la ubicación donde se tomó la foto', max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='proyectos.actividad', verbose_name='Actividad Relacionada')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Evidencia Fotográfica',
                'verbose_name_plural': 'Evidencias Fotográficas',
                'db_table': 'proyectos_evidencias_fotograficas',
                'ordering': ['-fecha_captura', '-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('numero_documento', models.CharField(blank=True, help_text='Número de radicado, consecutivo, etc.', max_length=100, null=True, verbose_name='Número de Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='proyectos/documentos/%Y/%m/', verbose_name='Archivo')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_proyectos', to='proyectos.tipodocumentoproyecto', verbose_name='Tipo de Documento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Documento de Proyecto',
                'verbose_name_plural': 'Documentos de Proyectos',
                'db_table': 'proyectos_documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTrabajador',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_desasignacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Desasignación')),
                ('rol_en_proyecto', models.CharField(blank=True, help_text='Ej: Operario, Ayudante, Supervisor', max_length=100, null=True, verbose_name='Rol en el Proyecto')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_proyecto', to='trabajadores.trabajadorpersonal', verbose_name='Trabajador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectos.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Asignación de Trabajador',
                'verbose_name_plural': 'Asignaciones de Trabajadores',
                'db_table': 'proyectos_asignaciones_trabajadores',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('proyecto', 'numero_actividad')},
        ),
    ]
