# Generated by Django 5.2.7 on 2025-11-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_cliente_activo_alter_cliente_nombre_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cantidad_ejecutada_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se actualiza automáticamente a partir de las actualizaciones de avance', max_digits=12, verbose_name='Cantidad Ejecutada Total'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='cantidad_programada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total prevista para esta actividad', max_digits=12, verbose_name='Cantidad Programada'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='unidad_medida',
            field=models.CharField(choices=[('M', 'Metro (m)'), ('M2', 'Metro cuadrado (m²)'), ('M3', 'Metro cúbico (m³)'), ('UND', 'Unidad'), ('GLB', 'Global'), ('pto', 'Punto'), ('KG', 'Kilogramo'), ('L', 'Litro'), ('H', 'Hora'), ('OTRO', 'Otro')], default='UND', max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.CreateModel(
            name='AvanceActividad',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_avance', models.DateField(verbose_name='Fecha del Avance')),
                ('cantidad_ejecutada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Ejecutada en el Período')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Avance de Actividad',
                'verbose_name_plural': 'Avances de Actividades',
                'db_table': 'proyectos_avances_actividades',
                'ordering': ['-fecha_avance', '-fecha_registro'],
            },
        ),
    ]
