# Generated by Django 5.2.7 on 2025-10-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorPersonal',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=20)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_expedicion_doc', models.DateField()),
                ('lugar_expedicion', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / No especifica')], max_length=10, null=True)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('UNION_LIBRE', 'Unión libre'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], max_length=20)),
                ('direccion_residencia', models.CharField(max_length=100)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('departamento_residencial', models.CharField(max_length=50)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('correo_personal', models.CharField(max_length=50)),
                ('grupo_sanguineo_rh', models.CharField(max_length=10)),
                ('nombres_padres', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('contacto_celular', models.CharField(max_length=100)),
                ('numero_hijos', models.IntegerField(blank=True, null=True)),
                ('cuenta_bancaria', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente'), ('OTRA', 'Otra')], max_length=20)),
                ('banco', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Trabajador (Datos Personales)',
                'verbose_name_plural': 'Trabajadores (Datos Personales)',
                'db_table': 'trabajadores_personal',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorLaboral',
            fields=[
                ('id_laboral', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('FIJO', 'Término Fijo'), ('OBRA', 'Obra o Labor'), ('PRESTACION', 'Prestación de Servicios')], max_length=50)),
                ('fecha_inicio_contrato', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jornada_laboral', models.CharField(choices=[('TIEMPO_COMPLETO', 'Tiempo completo'), ('MEDIO_TIEMPO', 'Medio tiempo'), ('TURNOS', 'Por turnos'), ('OTRA', 'Otra')], max_length=50)),
                ('sede_trabajo', models.CharField(max_length=100)),
                ('fecha_terminacion_contrato', models.DateField(blank=True, null=True)),
                ('motivo_terminacion', models.CharField(max_length=200)),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='registros_laborales', to='trabajadores.trabajadorpersonal')),
            ],
            options={
                'verbose_name': 'Registro Laboral',
                'verbose_name_plural': 'Registros Laborales',
                'db_table': 'trabajadores_laboral',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorDotacion',
            fields=[
                ('id_dotacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_dotacion', models.CharField(max_length=100)),
                ('talla', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='dotaciones', to='trabajadores.trabajadorpersonal')),
            ],
            options={
                'verbose_name': 'Dotación',
                'verbose_name_plural': 'Dotaciones',
                'db_table': 'trabajadores_dotacion',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorCurso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
                ('institucion', models.CharField(max_length=150)),
                ('fecha_inicio_curso', models.DateField()),
                ('fecha_fin_curso', models.DateField(blank=True, null=True)),
                ('certificado_url', models.CharField(blank=True, max_length=260, null=True)),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='trabajadores.trabajadorpersonal')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'trabajadores_cursos',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorAfiliaciones',
            fields=[
                ('id_afiliacion', models.AutoField(primary_key=True, serialize=False)),
                ('eps_nombre', models.CharField(max_length=100)),
                ('eps_numero_afiliacion', models.CharField(max_length=50)),
                ('fondo_pensiones_nombre', models.CharField(max_length=100)),
                ('fondo_pensiones_numero_afiliacion', models.CharField(max_length=50)),
                ('arl_nombre', models.CharField(max_length=100)),
                ('arl_numero_nombre', models.CharField(max_length=50)),
                ('caja_compensacion_nombre', models.CharField(max_length=100)),
                ('caja_compensacion_numero_afiliacion', models.CharField(max_length=50)),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones', to='trabajadores.trabajadorpersonal')),
            ],
            options={
                'verbose_name': 'Afiliación',
                'verbose_name_plural': 'Afiliaciones',
                'db_table': 'trabajadores_afiliaciones',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorRol',
            fields=[
                ('id_rol_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('rol_sistema', models.CharField(max_length=50)),
                ('estado_cuenta', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('BLOQUEADA', 'Bloqueada')], max_length=20)),
                ('ultimo_inicio_sesion', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='roles_sistema', to='trabajadores.trabajadorpersonal')),
            ],
            options={
                'verbose_name': 'Rol de Sistema',
                'verbose_name_plural': 'Roles de Sistema',
                'db_table': 'trabajadores_rol',
            },
        ),
    ]
