# Generated by Django 5.2.7 on 2025-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadorpersonal',
            old_name='departamento_residencial',
            new_name='departamento_residencia',
        ),
        migrations.AlterField(
            model_name='trabajadorpersonal',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PPT', 'Permiso por Proteccion Temporal'), ('PA', 'Pasaporte')], max_length=20),
        ),
    ]
