# Generated by Django 5.2.7 on 2025-10-13 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_rename_departamento_residencial_trabajadorpersonal_departamento_residencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadorpersonal',
            old_name='nombres_padres',
            new_name='nombres_madre',
        ),
        migrations.AddField(
            model_name='trabajadorpersonal',
            name='nombres_padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadorlaboral',
            name='motivo_terminacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadorpersonal',
            name='id_trabajador',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Solo dígitos, entre 5 y 20 caracteres.', regex='^\\d{5,20}$')], verbose_name='Número de Documento'),
        ),
    ]
