# Generated by Django 5.2.7 on 2025-10-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_rename_nombres_padres_trabajadorpersonal_nombres_madre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadorpersonal',
            old_name='contacto_emergencia',
            new_name='nombre_contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='trabajadorpersonal',
            name='contacto_nombre',
        ),
        migrations.AddField(
            model_name='trabajadorpersonal',
            name='numero_contacto_emergencia',
            field=models.CharField(default=3213123, max_length=40),
            preserve_default=False,
        ),
    ]
