# Generated by Django 5.2.7 on 2025-10-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_rename_contacto_emergencia_trabajadorpersonal_nombre_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadorpersonal',
            name='contacto_celular',
        ),
    ]
