# Generated by Django 5.2.7 on 2025-10-13 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0005_remove_trabajadorpersonal_contacto_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadorpersonal',
            name='numero_hijos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
