# Generated by Django 5.2.7 on 2025-10-27 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0006_alter_trabajadorpersonal_numero_hijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_curso', models.CharField(max_length=200, unique=True)),
                ('vigencia_dias', models.IntegerField(help_text='Días de vigencia del curso', validators=[django.core.validators.MinValueValidator(1)])),
                ('requiere_renovacion', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Tipos de Cursos',
                'db_table': 'tipos_cursos',
                'ordering': ['nombre_tipo_curso'],
            },
        ),
    ]
