# Generated by Django 5.2.7 on 2025-10-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0007_tipocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadorcurso',
            name='tipo_curso',
            field=models.ForeignKey(blank=True, help_text='Tipo de curso (opcional, para control de vigencia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_realizados', to='trabajadores.tipocurso'),
        ),
    ]
