# Generated by Django 5.2.7 on 2025-10-29 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0008_trabajadorcurso_tipo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDotacion',
            fields=[
                ('id_tipo_dotacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_dotacion', models.CharField(help_text='Ej: Casco, Botas de seguridad, Arnés', max_length=100, unique=True)),
                ('vida_util_dias', models.IntegerField(help_text='Días de vida útil estándar del elemento', validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_talla', models.BooleanField(default=True)),
                ('normativa_referencia', models.CharField(blank=True, help_text='Ej: Resolución 2400 de 1979', max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Dotación',
                'verbose_name_plural': 'Tipos de Dotaciones',
                'db_table': 'tipos_dotaciones',
                'ordering': ['nombre_tipo_dotacion'],
            },
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='dias_alerta_anticipada',
            field=models.IntegerField(default=30, help_text='Días antes del vencimiento para enviar alerta', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tipocurso',
            name='normativa_referencia',
            field=models.CharField(blank=True, help_text='Ej: Resolución 1409 de 2012 - Trabajo en Alturas', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trabajadorcurso',
            name='es_renovacion_de',
            field=models.ForeignKey(blank=True, help_text='Curso anterior que este renueva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='trabajadores.trabajadorcurso'),
        ),
        migrations.AddField(
            model_name='trabajadorcurso',
            name='numero_certificado',
            field=models.CharField(blank=True, help_text='Número del certificado oficial', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trabajadordotacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo (En uso)'), ('DEVUELTO', 'Devuelto'), ('DETERIORADO', 'Deteriorado'), ('EXTRAVIADO', 'Extraviado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajadordotacion',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajadordotacion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha calculada de vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='trabajadordotacion',
            name='motivo_devolucion',
            field=models.CharField(blank=True, choices=[('VENCIMIENTO', 'Vencimiento por tiempo'), ('DETERIORO', 'Deterioro'), ('PERDIDA', 'Pérdida o extravío'), ('CAMBIO_TALLA', 'Cambio de talla')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadorcurso',
            name='tipo_curso',
            field=models.ForeignKey(blank=True, help_text='Tipo de curso (requerido para control de vigencia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cursos_realizados', to='trabajadores.tipocurso'),
        ),
        migrations.AlterField(
            model_name='trabajadordotacion',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='trabajadordotacion',
            name='tipo_dotacion_catalogo',
            field=models.ForeignKey(blank=True, help_text='Tipo de dotación del catálogo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dotaciones_entregadas', to='trabajadores.tipodotacion'),
        ),
    ]
