# Generated by Django 5.2.7 on 2025-11-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0009_tipodotacion_tipocurso_dias_alerta_anticipada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodotacion',
            name='tallas_disponibles',
            field=models.TextField(blank=True, help_text='Tallas separadas por comas. Ej: 32,34,36,38 o S,M,L,XL', null=True),
        ),
    ]
