# Generated by Django 5.2.7 on 2025-11-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0010_tipodotacion_tallas_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadordotacion',
            name='talla',
            field=models.CharField(blank=True, help_text='Talla del elemento (validada según el tipo de dotación)', max_length=20),
        ),
    ]
