# Generated by Django 5.2.7 on 2025-11-04 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0011_alter_trabajadordotacion_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(help_text='Ej: Fotocopia Cédula, Certificado Curso, Afiliación EPS', max_length=100, verbose_name='Nombre del Tipo de Documento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de documento', null=True, verbose_name='Descripción')),
                ('es_obligatorio', models.BooleanField(default=False, help_text='Indica si este documento es obligatorio para todos los trabajadores', verbose_name='¿Es obligatorio?')),
                ('requiere_vigencia', models.BooleanField(default=False, help_text='Indica si el documento tiene fecha de vencimiento', verbose_name='¿Requiere control de vigencia?')),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ej: bi-file-earmark-text, bi-card-checklist', max_length=50, null=True, verbose_name='Icono Bootstrap')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que se muestra en el detalle del trabajador (menor = primero)', verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá disponible para asignar', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipos_documentos',
                'ordering': ['orden_visualizacion', 'nombre_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='TrabajadorDocumento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(help_text='Archivo PDF, imagen (JPG, PNG) u otro formato', upload_to='documentos_trabajadores/%Y/%m/', verbose_name='Archivo')),
                ('nombre_archivo_original', models.CharField(blank=True, help_text='Se guarda automáticamente al subir el archivo', max_length=255, verbose_name='Nombre del archivo original')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('vigencia_desde', models.DateField(blank=True, help_text='Fecha de inicio de vigencia (opcional)', null=True, verbose_name='Vigente desde')),
                ('vigencia_hasta', models.DateField(blank=True, help_text='Fecha de vencimiento del documento (opcional)', null=True, verbose_name='Vigente hasta')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el documento', null=True, verbose_name='Observaciones')),
                ('cargado_por', models.CharField(blank=True, help_text='Usuario que cargó el documento', max_length=100, null=True, verbose_name='Cargado por')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='trabajadores.trabajadorpersonal', verbose_name='Trabajador')),
                ('tipo_documento', models.ForeignKey(help_text='Seleccione el tipo de documento del catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_trabajadores', to='trabajadores.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento del Trabajador',
                'verbose_name_plural': 'Documentos de Trabajadores',
                'db_table': 'trabajadores_documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
