# Generated by Django 5.2.7 on 2025-11-06 02:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoProveedor',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(help_text='Ej: RUT, Cámara de Comercio, Certificado ISO', max_length=100, unique=True, verbose_name='Nombre del tipo de documento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de documento', null=True, verbose_name='Descripción')),
                ('es_obligatorio', models.BooleanField(default=False, help_text='Indica si este documento es obligatorio para todos los proveedores', verbose_name='¿Es obligatorio?')),
                ('requiere_vigencia', models.BooleanField(default=False, help_text='Indica si el documento tiene fecha de vencimiento', verbose_name='¿Requiere control de vigencia?')),
                ('dias_alerta_vencimiento', models.IntegerField(default=30, help_text='Días antes del vencimiento para generar alerta', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días de alerta antes del vencimiento')),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ej: bi-file-earmark-text, bi-card-checklist', max_length=50, null=True, verbose_name='Icono Bootstrap')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que se muestra en el detalle del proveedor (menor = primero)', verbose_name='Orden de visualización')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá disponible para asignar', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Proveedor',
                'verbose_name_plural': 'Tipos de Documentos de Proveedores',
                'db_table': 'tipos_documentos_proveedores',
                'ordering': ['orden_visualizacion', 'nombre_tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id_tipo_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(help_text='Ej: Fabricante, Distribuidor, Importador', max_length=100, unique=True, verbose_name='Nombre del tipo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo de proveedor', null=True, verbose_name='Descripción')),
                ('requiere_certificaciones', models.BooleanField(default=False, help_text='Indica si este tipo de proveedor debe tener certificaciones específicas', verbose_name='¿Requiere certificaciones especiales?')),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ej: bi-building, bi-truck, bi-globe', max_length=50, null=True, verbose_name='Icono Bootstrap')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá disponible para asignar', verbose_name='Activo')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que se muestra en listados (menor = primero)', verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Proveedor',
                'verbose_name_plural': 'Tipos de Proveedores',
                'db_table': 'tipos_proveedores',
                'ordering': ['orden_visualizacion', 'nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProveedor',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(help_text='Ej: Lonas y Telas, Estructuras Metálicas', max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de los productos/servicios de esta categoría', null=True, verbose_name='Descripción')),
                ('color_badge', models.CharField(default='primary', help_text='Color Bootstrap: primary, success, danger, warning, info, secondary', max_length=20, verbose_name='Color del badge')),
                ('icono_bootstrap', models.CharField(blank=True, help_text='Ej: bi-basket, bi-box, bi-tools', max_length=50, null=True, verbose_name='Icono Bootstrap')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparecerá disponible para asignar', verbose_name='Activo')),
                ('orden_visualizacion', models.IntegerField(default=0, help_text='Orden en que se muestra en listados (menor = primero)', verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria_padre', models.ForeignKey(blank=True, help_text='Para crear jerarquía de categorías (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='proveedores.categoriaproveedor', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría de Proveedor',
                'verbose_name_plural': 'Categorías de Proveedores',
                'db_table': 'categorias_proveedores',
                'ordering': ['orden_visualizacion', 'nombre_categoria'],
            },
        ),
    ]
