# Generated by Django 5.2.7 on 2025-11-09 19:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoproveedor',
            options={'ordering': ['-es_contacto_principal', 'apellidos', 'nombres'], 'verbose_name': 'Contacto de Proveedor', 'verbose_name_plural': 'Contactos de Proveedores'},
        ),
        migrations.AlterUniqueTogether(
            name='documentoproveedor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactoproveedor',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='contactoproveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 9, 19, 25, 51, 207807), verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentoproveedor',
            name='estado_documento',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por vencer'), ('VENCIDO', 'Vencido'), ('NO_APLICA', 'No aplica')], default='VIGENTE', max_length=20, verbose_name='Estado del Documento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='acepta_credito',
            field=models.BooleanField(default=True, help_text='¿El proveedor acepta ventas a crédito?', verbose_name='Acepta Crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='actividad_economica',
            field=models.CharField(blank=True, help_text='Descripción de la actividad económica principal', max_length=255, null=True, verbose_name='Actividad Económica'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_ciiu',
            field=models.CharField(blank=True, help_text='Clasificación Industrial Internacional Uniforme', max_length=10, null=True, verbose_name='Código CIIU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_facturacion',
            field=models.EmailField(blank=True, help_text='Email específico para envío de facturas', max_length=254, null=True, verbose_name='Email de Facturación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes 8:00 AM - 5:00 PM', max_length=200, null=True, verbose_name='Horario de Atención'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='metodos_pago_aceptados',
            field=models.CharField(blank=True, help_text='Ej: Efectivo, Transferencia, Cheque, Tarjeta', max_length=500, null=True, verbose_name='Métodos de Pago Aceptados'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais_origen',
            field=models.CharField(default='Colombia', help_text='País donde está constituida la empresa', max_length=100, verbose_name='País de Origen'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='responsabilidad_fiscal',
            field=models.CharField(choices=[('NO_RESPONSABLE', 'No Responsable de IVA'), ('RESPONSABLE_IVA', 'Responsable de IVA'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'), ('AUTORRETENEDOR', 'Autorretenedor'), ('REGIMEN_SIMPLE', 'Régimen Simple de Tributación')], default='RESPONSABLE_IVA', max_length=50, verbose_name='Responsabilidad Fiscal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='titular_cuenta',
            field=models.CharField(blank=True, help_text='Nombre del titular de la cuenta bancaria', max_length=200, null=True, verbose_name='Titular de la Cuenta'),
        ),
        migrations.AddField(
            model_name='tipodocumentoproveedor',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='tipoproveedor',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='contactoproveedor',
            name='area_responsabilidad',
            field=models.CharField(blank=True, help_text='Área o departamento del que es responsable', max_length=100, null=True, verbose_name='Área de Responsabilidad'),
        ),
        migrations.AlterField(
            model_name='contactoproveedor',
            name='es_contacto_principal',
            field=models.BooleanField(default=False, help_text='Solo puede haber un contacto principal por proveedor', verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='documentoproveedor',
            name='archivo',
            field=models.FileField(help_text='Archivo del documento (PDF, Word, Excel, Imagen)', upload_to='proveedores/documentos/%Y/%m/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentoproveedor',
            name='entidad_emisora',
            field=models.CharField(blank=True, help_text='Organismo o entidad que emitió el documento', max_length=200, null=True, verbose_name='Entidad Emisora'),
        ),
        migrations.AlterField(
            model_name='documentoproveedor',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='proveedores.tipodocumentoproveedor', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentoproveedor',
            name='nombre_archivo_original',
            field=models.CharField(max_length=255, verbose_name='Nombre Original del Archivo'),
        ),
        migrations.RemoveField(
            model_name='documentoproveedor',
            name='cargado_por',
        ),
        migrations.RemoveField(
            model_name='documentoproveedor',
            name='estado',
        ),
    ]
