# Generated by Django 5.2.7 on 2025-11-07 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(help_text='Nombre legal de la empresa', max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre con el que se conoce comercialmente', max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('RUT', 'RUT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='NIT', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(help_text='NIT, RUT o documento de identificación', max_length=20, unique=True, verbose_name='Número de Documento')),
                ('digito_verificacion', models.CharField(blank=True, help_text='Solo para NIT', max_length=1, null=True, verbose_name='Dígito de Verificación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('EN_EVALUACION', 'En evaluación')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('regimen_tributario', models.CharField(choices=[('COMUN', 'Régimen Común'), ('SIMPLIFICADO', 'Régimen Simplificado'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente')], default='COMUN', max_length=30, verbose_name='Régimen Tributario')),
                ('responsabilidad_fiscal', models.CharField(choices=[('IVA', 'Responsable de IVA'), ('NO_IVA', 'No responsable de IVA'), ('RETENEDOR', 'Agente de retención')], default='IVA', max_length=20, verbose_name='Responsabilidad Fiscal')),
                ('actividad_economica', models.CharField(blank=True, help_text='Descripción de la actividad principal', max_length=200, null=True, verbose_name='Actividad Económica')),
                ('codigo_ciiu', models.CharField(blank=True, help_text='Código de clasificación industrial', max_length=10, null=True, verbose_name='Código CIIU')),
                ('pais_origen', models.CharField(default='Colombia', max_length=50, verbose_name='País de Origen')),
                ('direccion_principal', models.CharField(max_length=200, verbose_name='Dirección Principal')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('pais', models.CharField(default='Colombia', max_length=50, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Secundario')),
                ('email_principal', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('email_facturacion', models.EmailField(blank=True, help_text='Email para envío de facturas', max_length=254, null=True, verbose_name='Email de Facturación')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('horario_atencion', models.TextField(blank=True, help_text='Ej: Lunes a Viernes 8:00 AM - 5:00 PM', null=True, verbose_name='Horario de Atención')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, null=True, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('titular_cuenta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular de la Cuenta')),
                ('plazo_entrega_dias', models.IntegerField(default=0, help_text='Días promedio de entrega', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plazo de Entrega (días)')),
                ('tiempo_credito_dias', models.IntegerField(default=0, help_text='Días de crédito que ofrece', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Crédito (días)')),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento por pronto pago', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Pronto Pago (%)')),
                ('monto_minimo_pedido', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo de compra', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mínimo de Pedido')),
                ('acepta_credito', models.BooleanField(default=False, help_text='Si el proveedor maneja ventas a crédito', verbose_name='¿Acepta Crédito?')),
                ('metodos_pago_aceptados', models.TextField(blank=True, help_text='Ej: Efectivo, Transferencia, Cheque, Tarjeta', null=True, verbose_name='Métodos de Pago Aceptados')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Compra')),
                ('total_compras_historico', models.DecimalField(decimal_places=2, default=0, help_text='Suma total de todas las compras realizadas', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Compras Histórico')),
                ('calificacion_promedio', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación promedio (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calificación Promedio')),
                ('numero_evaluaciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Evaluaciones')),
                ('registrado_por', models.CharField(blank=True, help_text='Usuario que registró el proveedor', max_length=100, null=True, verbose_name='Registrado Por')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('categoria_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_categoria_principal', to='proveedores.categoriaproveedor', verbose_name='Categoría Principal')),
                ('tipo_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.tipoproveedor', verbose_name='Tipo de Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
