# Generated by Django 5.2.7 on 2025-11-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(help_text='Ej: Gerente de Ventas, Coordinador de Logística', max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, help_text='Ej: Ventas, Producción, Administración', max_length=100, null=True, verbose_name='Departamento')),
                ('area_responsabilidad', models.CharField(choices=[('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('FACTURACION', 'Facturación'), ('TECNICO', 'Técnico'), ('LOGISTICA', 'Logística'), ('GERENCIA', 'Gerencia'), ('OTRO', 'Otro')], default='VENTAS', max_length=20, verbose_name='Área de Responsabilidad')),
                ('telefono_directo', models.CharField(blank=True, help_text='Extensión o línea directa (opcional)', max_length=20, null=True, verbose_name='Teléfono Directo')),
                ('telefono_celular', models.CharField(max_length=20, verbose_name='Teléfono Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('es_contacto_principal', models.BooleanField(default=False, help_text='Solo puede haber un contacto principal por proveedor', verbose_name='¿Es contacto principal?')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el contacto', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedores',
                'db_table': 'contactos_proveedores',
                'ordering': ['-es_contacto_principal', 'nombre_completo'],
            },
        ),
    ]
