# Generated by Django 5.2.7 on 2025-11-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_contactoproveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumentoproveedor',
            name='dias_alerta_vencimiento',
            field=models.IntegerField(blank=True, default=30, help_text='Días antes del vencimiento para enviar alertas (solo si requiere vigencia)', null=True, verbose_name='Días de Alerta antes del Vencimiento'),
        ),
    ]
